### PR TITLE
fix(doc): inaccurate doc of kong.nginx.get_var

### PR DESCRIPTION
**Pull request by StarlightIbuki**
Fix a doc issue found from #107

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Shouldn't `get_var` expect a parameter (to indicate what variable to get)?

**Comment by StarlightIbuki** [comment]
@michaelarnauts Correct. The doc is generated with a script and we need to fix it in another place.

**Comment by StarlightIbuki** [comment]
The doc is fixed. Closing.

**Comment by michaelarnauts** [comment]
Does anything more then the doc need changing? I've tried the suggestion from the linked issue, but got the message "API disabled in the current context".

**Comment by StarlightIbuki** [comment]
@michaelarnauts Sorry for the confusion. Replying in that ticket.

**Pull request closed without merging**
